### ISSUE TITLE
Script tag of polyfill is not being transformed

### ISSUE THREAD

**Issue by Gwokhov** [chenxch/vite-plugin-dynamic-base#7] opened 2022-05-09 05:37 UTC
This .html file is the product from the example after build, it looks like the script tag of legacy polyfill is not being transformed.

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/30198039/167346524-4d9adde9-f5a8-4b11-bf16-d6adcc743dbd.png">

**Comment by chenxch** [comment] 2022-05-09 05:38
Can you tell me which version you are using?

**Comment by Gwokhov** [comment] 2022-05-09 05:41
> Can you tell me which version you are using?

0.4.0

**Comment by chenxch** [comment] 2022-05-09 05:43
> > Can you tell me which version you are using?
> 
> 0.4.0

Okay, the code should have been rolled back by me, I'll update a fix version right away and let you know.

**Comment by chenxch** [comment] 2022-05-09 05:46
No no, I remembered it, this is how it is handled here, because it is nomodule, it will not be executed by default, it is loaded through the above script to get the src attribute, it turns out to be `n.src=e .src`, I processed it as `n.src=window.__dynamic_base__+e.getAttribute('src')`

**Comment by chenxch** [comment] 2022-05-09 05:57
Can you describe the problem you are currently facing?

**Comment by chenxch** [comment] 2022-05-09 06:02
@Gwokhov I think I know where the problem is, nomodule will not take effect in backward browsers, it will be executed directly. I will fix it as soon as possible, thank you very much for your feedback.

**Comment by Gwokhov** [comment] 2022-05-09 06:25
> 

It does, but it runs in module mode, and `System.import` is not in the environment. 🧐

**Comment by Gwokhov** [comment] 2022-05-09 07:15
> @Gwokhov I think I know where the problem is, nomodule will not take effect in backward browsers, it will be executed directly. I will fix it as soon as possible, thank you very much for your feedback.

I tested in IE11 and IE would not execute the script tag with `type=module` which was injecting dynamic base code, so the polyfill script was linked to the wrong resource.

**Comment by chenxch** [comment] 2022-05-09 07:17
Yes, I also found this problem through IE11, I will think about it later if I can solve this problem.

**Comment by zhoujinfu** [comment] 2022-05-09 10:25
> Yes, I also found this problem through IE11, I will think about it later if I can solve this problem.

Same as vite-legacy-entry, we can change the vite-legacy-polyfill src attribute to data-src and using systemjs to import the __dynamic_base__ + el.src, this may fix the issue.

**Comment by zhoujinfu** [comment] 2022-05-09 11:39
vite-legacy works with legacy browsers by:

```html
<script type="module">!function(){if(window.__vite_is_dynamic_import_support)return;
    console.warn("vite: loading legacy build because dynamic import is unsupported, syntax error above should be ignored");
    var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");
    n.src=window.__dynamic_base__+e.src,n.onload=function(){
      System.import(window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))
    },
    document.body.appendChild(n)}();</script>
```

the script will load `vite-legacy-polyfill` by create a brand new `<script />` with `__dynamic_base__` prefix.

**Comment by zhoujinfu** [comment] 2022-05-09 11:40
`<script nomdule />`s will not be execute by browsers.

**Comment by chenxch** [comment] 2022-05-09 12:29
> vite-legacy works with legacy browsers by:
> 
> ```
> <script type="module">!function(){if(window.__vite_is_dynamic_import_support)return;
>     console.warn("vite: loading legacy build because dynamic import is unsupported, syntax error above should be ignored");
>     var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");
>     n.src=window.__dynamic_base__+e.src,n.onload=function(){
>       System.import(window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))
>     },
>     document.body.appendChild(n)}();</script>
> ```
> 
> the script will load `vite-legacy-polyfill` by create a brand new `<script />` with `__dynamic_base__` prefix.

I am also planning to make another loader in the body.

**Comment by chenxch** [comment] 2022-05-09 12:51
> `<script nomdule />`s will not be execute by browsers.

Will be executed in IE11.

**Comment by zhoujinfu** [comment] 2022-05-09 13:27
how about transform legacy scripts from:

```html
<script nomodule id="vite-legacy-polyfill" src="/assets/polyfills-legacy.c9aac887.js"></script>
  <script nomodule id="vite-legacy-entry" data-src="/assets/index-legacy.b6066e67.js">System.import(window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))</script>
```

to:

```html
<script nomodule id="vite-legacy-polyfill" src="/assets/polyfills-legacy.c9aac887.js">
!(function() {
  var e = document.createElement('script')
  e.src = window.__dynamic_base__ + "";
  e.onload = function() {
    System.import(window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))
  };
  document.body.appendChild(e)
})();
</script>
<script nomodule id="vite-legacy-entry" data-src="/assets/index-legacy.b6066e67.js"></script>
```

**Comment by Gwokhov** [comment] 2022-05-09 14:56
> @Gwokhov You can try version 0.4.1

Not work, the .html was blocked at `#vite-legacy-entry` script tag, cause `System` is defined in polyfill, maybe it is not a good idea to patch at the bottom.

**Comment by chenxch** [comment] 2022-05-09 15:50
![image](https://user-images.githubusercontent.com/23251408/167448013-d39c5c4a-85c1-4617-afc9-4bbe7214a2a4.png)
It seems that the results we got are not the same, it's okay, I will deal with it more comprehensively, and leave a message for you later, you can try the new version tomorrow morning.

**Comment by chenxch** [comment] 2022-05-09 17:36
@Gwokhov  You can try version 0.4.2 through @zhoujinfu  scheme

**Comment by Gwokhov** [comment] 2022-05-10 06:01
> @Gwokhov You can try version 0.4.2 through @zhoujinfu scheme

Thanks a lot, it works as expected now.

**Comment by chenxch** [comment] 2022-05-10 11:28
I'll close this question then, thank you for your use and feedback, and have a nice day.

**Closed** 2022-05-10 11:28 UTC
