### ISSUE TITLE
not support @vitejs/plugin-legacy@2.2.0

### ISSUE THREAD

**Issue by feawesome** [chenxch/vite-plugin-dynamic-base#16] opened 2022-10-13 12:26 UTC
this.is legacy config

<img width="480" alt="image" src="https://user-images.githubusercontent.com/17822851/195595095-34a34ca5-9162-4d0d-95fa-76a493f7ec98.png">

there is no these code in final html

` <script id="vite-legacy-entry" data-src="assets/app-download-legacy.93713ccb.js">System.import(window.__dynamic_base__+document.getElementById('vite-legacy-entry').getAttribute('data-src'))</script>`

**Comment by chenxch** [comment] 2022-10-13 15:12
Is it convenient to provide the following plug-in version and a demo?

**Comment by feawesome** [comment] 2022-10-14 02:38
> 

my plugin version is 0.2.0，

this.is my vite.config.js

`    base: './',
    plugins: [
        vue(),
        dynamicBase({
            publicPath: 'window.__dynamic_base__',
            transformIndexHtml: true
        }),
        legacy({
            // targets: ['defaults', 'not IE 11'],
            targets: ['chrome >= 66'],
            modernPolyfills: true
        })
    ],`

**Comment by chenxch** [comment] 2022-10-14 03:03
You can try to upgrade `vite-plugin-dynamic-base` to the `latest` version first, my impression is that a legacy-related problem has been fixed.

**Comment by chenxch** [comment] 2022-10-14 03:05
https://github.com/chenxch/vite-plugin-dynamic-base/blob/main/CHANGELOG.md#044

**Comment by chenxch** [comment] 2022-10-14 04:04
If the problem is solved, you can close this issue.

**Closed** 2022-10-14 06:51 UTC
